# This file was generated by GoReleaser. DO NOT EDIT.
cask "heydb" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "6828c49304c365be560acd550c5436c9454db637986247c04d85188dc9002ef6"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "292f745a8179925aa38405e232d438d89c5cd81d0a119ef142b7d1c39c8e8829"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fed5f2f63ca24524a5c001b9850a169fdefc61341fce95fc818da604673592bc"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea8d78a5ff311981379dd18d2c27cc903ae2f1bad7aeada8d1c7ae7e2cf803a6"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "heydb"
  desc "Introspect MySQL schemas and serve them to AI agents via MCP"
  homepage "https://github.com/pvidaal07/heydb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heydb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/heydb"]
    end
  end

  # No zap stanza required

end
