# This file was generated by GoReleaser. DO NOT EDIT.
cask "heydb" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "f0469e0ff69eb69ecf99960346ba5945d8df6deaaab2b1a70536592dc38da02e"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f8621ee46b9fe900906193afb9705be7faf00eb26a43d59d8b98e8a3d60faf72"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0562a84e0a864042950181d596d4982698e624e7264c9c9bf18961b7f3c6008"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e438fd87b661e70f7d16f1ff7582c39ff2de1c20d35c07ed57f8d6d14e51891c"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "heydb"
  desc "Introspect MySQL schemas and serve them to AI agents via MCP"
  homepage "https://github.com/pvidaal07/heydb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heydb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/heydb"]
    end
  end

  # No zap stanza required

end
