# This file was generated by GoReleaser. DO NOT EDIT.
cask "heydb" do
  version "1.0.1"

  on_macos do
    on_intel do
      sha256 "6b320977e5d64fbae1e84b49879344e97cbaa2e6c7f7d60b81fbcb4be97cab27"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "abe15daa9d76df05093b10c380366d766197551aa9d83a1a7ac4da203d873fe0"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ba7789a303f172e567ebfc6fde1430e5d4abef7857175be6dce591390bc2d1e"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "600bb2d3068a51369b96398bfc5d3736a6ed30db80ce6e394d58f60c0c3e3000"
      url "https://github.com/pvidaal07/heydb/releases/download/v#{version}/heydb_#{version}_linux_arm64.tar.gz"
    end
  end

  name "heydb"
  desc "Introspect MySQL schemas and serve them to AI agents via MCP"
  homepage "https://github.com/pvidaal07/heydb"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "heydb"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/heydb"]
    end
  end

  # No zap stanza required

end
